
CREATE TABLE `tr_member_acct_transfer_earnings_logs` (
  `member_transfer_id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `from_member_id` int(11) DEFAULT NULL,
  `to_member_id` int(11) DEFAULT NULL,
  `account_id` varchar(64) DEFAULT NULL,
  `referral_bonus` decimal(10,0) DEFAULT '0',
  `transfer_referral_bonus` decimal(10,0) DEFAULT '0',
  `pairing_bonus_sp` decimal(10,0) DEFAULT '0',
  `transfer_pairing_bonus_sp` decimal(10,0) DEFAULT '0',
  `gift_cheque_sp` decimal(10,0) DEFAULT '0',
  `transfer_gift_cheque_sp` decimal(10,0) DEFAULT '0',
  `pairing_bonus_vp` decimal(10,0) DEFAULT '0',
  `transfer_pairing_bonus_vp` decimal(10,0) DEFAULT '0',
  `gift_cheque_vp` decimal(10,0) DEFAULT '0',
  `transfer_gift_cheque_vp` decimal(10,0) DEFAULT '0',
  `pairing_bonus_tp` decimal(10,0) unsigned DEFAULT '0',
  `transfer_pairing_bonus_tp` decimal(10,0) unsigned DEFAULT '0',
  `gift_cheque_tp` decimal(10,0) DEFAULT '0',
  `transfer_gift_cheque_tp` decimal(10,0) DEFAULT '0',
  `pairing_bonus_rs` decimal(10,0) DEFAULT '0',
  `transfer_pairing_bonus_rs` decimal(10,0) DEFAULT '0',
  `gift_cheque_rs` decimal(10,0) DEFAULT '0',
  `transfer_gift_cheque_rs` decimal(10,0) DEFAULT '0',
  `unilevel_commission` decimal(10,0) DEFAULT '0',
  `transfer_unilevel_commission` decimal(10,0) DEFAULT '0',
  `with_earnings` int(1) DEFAULT NULL,
  `insert_timestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`member_transfer_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `tr_member_acct_transfer_earnings_per_type_logs` (
  `member_transfer_id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `from_member_id` int(11) DEFAULT NULL,
  `to_member_id` int(11) DEFAULT NULL,
  `account_id` varchar(64) DEFAULT NULL,
  `type_id` int(11) DEFAULT NULL,
  `pairing_bonus` decimal(10,0) DEFAULT NULL,
  `transfer_pairing_bonus` decimal(10,0) DEFAULT NULL,
  `gift_cheque` decimal(10,0) DEFAULT NULL,
  `transfer_gift_cheque` decimal(10,0) DEFAULT NULL,
  `with_earnings` int(1) DEFAULT NULL,
  `insert_timestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`member_transfer_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
