CREATE TABLE `po_member_account_commissions` (
  `commission_id` int(11) NOT NULL AUTO_INCREMENT,
  `payout_id` int(10) unsigned NOT NULL DEFAULT '0',
  `payout_type` varchar(64) COLLATE utf8_unicode_ci DEFAULT NULL,
  `member_id` int(10) unsigned NOT NULL DEFAULT '0',
  `account_id` varchar(64) COLLATE utf8_unicode_ci DEFAULT NULL,
  `gross` decimal(10,2) DEFAULT '0.00',
  `witholding_tax` decimal(10,2) DEFAULT '0.00',
  `net_of_tax` decimal(10,2) DEFAULT '0.00',
  `balance` decimal(10,2) DEFAULT '0.00',
  `total` decimal(10,2) DEFAULT '0.00',
  `cash_card` varchar(64) COLLATE utf8_unicode_ci NOT NULL,
  `account_status` varchar(15) COLLATE utf8_unicode_ci DEFAULT NULL,
  `commission_status` varchar(15) COLLATE utf8_unicode_ci DEFAULT NULL,
  `start_date` date DEFAULT NULL,
  `end_date` date DEFAULT NULL,
  `remarks` text COLLATE utf8_unicode_ci,
  `insert_timestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`commission_id`),
  KEY `member_id` (`member_id`),
  KEY `account_id` (`account_id`),
  KEY `start_date` (`start_date`),
  KEY `end_date` (`end_date`),
  KEY `start_date_2` (`start_date`,`end_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;