create table ph_funds_to_paycard (
  `funds_to_paycard_id` int(11) NOT NULL AUTO_INCREMENT,
  `member_id` int(11),
  `last_name` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `first_name` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `middle_name` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL, 
  `gross` decimal(10,2) DEFAULT '0.00',
  `gcep` decimal(10,2) DEFAULT '0.00',
  `net_of_gcep` decimal(10,2) DEFAULT '0.00',
  `wtax` decimal(10,2) DEFAULT '0.00',
  `net_of_wtax` decimal(10,2) DEFAULT '0.00',
  `deduction1` decimal(10,2) DEFAULT '0.00',
  `deduction2` decimal(10,2) DEFAULT '0.00',
  `final_commission` decimal(10,2) DEFAULT '0.00',
  `cash_card` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL, 
  `start_date` date DEFAULT NULL, 
  `end_date` date DEFAULT NULL, 
  `funds_before` decimal(10,2) DEFAULT '0.00',
  `funds_after` decimal(10,2) DEFAULT '0.00',
  `status` varchar(20) COLLATE utf8_unicode_ci DEFAULT 'PENDING', 
  `insert_timestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_timestamp` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`funds_to_paycard_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
