ALTER TABLE  `is_sp_cards` ADD  `autogenerated` TINYINT( 1 ) NOT NULL DEFAULT  '0' AFTER  `issued_to` ;

ALTER TABLE  `is_rs_cards` ADD  `autogenerated` TINYINT( 1 ) NOT NULL DEFAULT  '0' AFTER  `issued_to` ;

UPDATE is_sp_cards SET `autogenerated` = 1 where card_id NOT REGEXP '^-?[0-9]+$';

UPDATE is_rs_cards SET `autogenerated` = 1 where card_id NOT REGEXP '^-?[0-9]+$';