INSERT INTO `rf_settings` (`slug`, `value`, `default`, `system_code`, `is_locked`)
VALUES
	('disable_autogenerated_cards_email', '1', '1', 'system', 0);
	
	

INSERT INTO `sm_contents` (`parent_content_id`, `user_id`, `title`, `slug`, `body`, `thumb`, `excerpt`, `is_active`, `path`, `content_type`)
VALUES
	(0, 0, 'Auto-Generated Cards', 'auto-generated-cards', '<p>Hi {@=customer_name},</p>\n<p>For your transaction <strong>{@=transaction_code}</strong>, the following cards were generated:</p>\n<table style=\"width: 50%;\" cellspacing=\"2\" cellpadding=\"2\">\n<thead>\n</thead>\n<tr><th>Control Code</th><th>RSRN</th><th>Type</th></tr>\n<tbody>\n<p>{@=orders_html}</p>\n</tbody>\n</table>\n<p><br /><br /></p>\n<p>Thanks,<br />Vital-C.com</p>', '', '', 1, '', 'email_template');
	

