CREATE TABLE `cm_member_payouts_backups` (
  `transaction_id` int(11) NOT NULL AUTO_INCREMENT,
  `payout_type` varchar(64) COLLATE utf8_unicode_ci DEFAULT NULL,
  `member_id` int(10) unsigned NOT NULL DEFAULT '0',
  `gross` decimal(10,2) DEFAULT '0.00',
  `gcep` decimal(10,2) DEFAULT '0.00',
  `net_of_gcep` decimal(10,2) DEFAULT '0.00',
  `witholding_tax` decimal(10,2) DEFAULT '0.00',
  `net_of_tax` decimal(10,2) DEFAULT '0.00',
  `balance` decimal(10,2) DEFAULT '0.00',
  `deduction2` decimal(10,2) DEFAULT '0.00',
  `card_fee` decimal(10,2) DEFAULT '0.00',
  `adjustments` decimal(10,2) DEFAULT '0.00',
  `total_amount` decimal(10,2) DEFAULT '0.00',
  `funds_before` decimal(10,2) NOT NULL DEFAULT '0.00',
  `funds_after` decimal(10,2) NOT NULL DEFAULT '0.00',
  `funds_variance_before` decimal(10,2) NOT NULL DEFAULT '0.00',
  `funds_variance_after` decimal(10,2) NOT NULL DEFAULT '0.00',
  `service_depot` varchar(64) COLLATE utf8_unicode_ci DEFAULT NULL,
  `group_name` varchar(64) COLLATE utf8_unicode_ci DEFAULT NULL,
  `cash_card` varchar(64) COLLATE utf8_unicode_ci NOT NULL,
  `is_corpo_sharing` tinyint(1) NOT NULL DEFAULT '0',
  `check_release` tinyint(1) NOT NULL DEFAULT '0',
  `is_on_hold` tinyint(1) NOT NULL DEFAULT '0',
  `status` varchar(15) COLLATE utf8_unicode_ci DEFAULT NULL,
  `start_date` date DEFAULT NULL,
  `end_date` date DEFAULT NULL,
  `user_id` int(10) unsigned NOT NULL DEFAULT '0',
  `remarks` text COLLATE utf8_unicode_ci,
  `insert_timestamp` timestamp,
  `backup_insert_timestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`transaction_id`),
  KEY `member_id` (`member_id`),
  KEY `start_date` (`start_date`),
  KEY `end_date` (`end_date`),
  KEY `start_date_2` (`start_date`,`end_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;



